services:
  prompts:
    build:
      context: .
      dockerfile: ./apps/prompts/Dockerfile
      target: development
    command: pnpm run start:dev prompts
    env_file:
      - ./apps/prompts/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
